// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: backend/game/v1/game.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGamesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        int32                  `protobuf:"varint,1,opt,name=site_id,json=siteId,proto3" json:"site_id" dc:"站点ID"`                        // 站点ID
	SearchBalance bool                   `protobuf:"varint,2,opt,name=search_balance,json=searchBalance,proto3" json:"search_balance" dc:"是否查询余额"` // 是否查询余额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGamesReq) Reset() {
	*x = GetGamesReq{}
	mi := &file_backend_game_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGamesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGamesReq) ProtoMessage() {}

func (x *GetGamesReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_game_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGamesReq.ProtoReflect.Descriptor instead.
func (*GetGamesReq) Descriptor() ([]byte, []int) {
	return file_backend_game_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *GetGamesReq) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *GetGamesReq) GetSearchBalance() bool {
	if x != nil {
		return x.SearchBalance
	}
	return false
}

type GetGamesRes struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          map[int32]*GameTypeList `protobuf:"bytes,1,rep,name=data,proto3" json:"data" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" dc:"按游戏类型分组的游戏列表"` // 按游戏类型分组的游戏列表
	Count         int32                   `protobuf:"varint,2,opt,name=count,proto3" json:"count" dc:"总数量"`                                                                                  // 总数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGamesRes) Reset() {
	*x = GetGamesRes{}
	mi := &file_backend_game_v1_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGamesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGamesRes) ProtoMessage() {}

func (x *GetGamesRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_game_v1_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGamesRes.ProtoReflect.Descriptor instead.
func (*GetGamesRes) Descriptor() ([]byte, []int) {
	return file_backend_game_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *GetGamesRes) GetData() map[int32]*GameTypeList {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetGamesRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GameTypeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*GameInfo            `protobuf:"bytes,1,rep,name=games,proto3" json:"games" dc:"游戏列表"` // 游戏列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameTypeList) Reset() {
	*x = GameTypeList{}
	mi := &file_backend_game_v1_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameTypeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameTypeList) ProtoMessage() {}

func (x *GameTypeList) ProtoReflect() protoreflect.Message {
	mi := &file_backend_game_v1_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameTypeList.ProtoReflect.Descriptor instead.
func (*GameTypeList) Descriptor() ([]byte, []int) {
	return file_backend_game_v1_game_proto_rawDescGZIP(), []int{2}
}

func (x *GameTypeList) GetGames() []*GameInfo {
	if x != nil {
		return x.Games
	}
	return nil
}

type GameInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"游戏ID"`                                // 游戏ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name" dc:"游戏名称"`                             // 游戏名称
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status" dc:"状态 1=启用 0=禁用"`                // 状态 1=启用 0=禁用
	Sort          int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort" dc:"排序"`                              // 排序
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type" dc:"游戏类型 1=体育 2=彩票 3=真人 4=电子游戏 5=棋牌"` // 游戏类型 1=体育 2=彩票 3=真人 4=电子游戏 5=棋牌
	Platform      string                 `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform" dc:"平台标识"`                     // 平台标识
	Code          string                 `protobuf:"bytes,7,opt,name=code,proto3" json:"code" dc:"游戏标识"`                             // 游戏标识
	ImageCode     string                 `protobuf:"bytes,8,opt,name=image_code,json=imageCode,proto3" json:"image_code" dc:"图片标识"`  // 图片标识
	DbName        string                 `protobuf:"bytes,9,opt,name=db_name,json=dbName,proto3" json:"db_name" dc:"数据表名称"`          // 数据表名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameInfo) Reset() {
	*x = GameInfo{}
	mi := &file_backend_game_v1_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfo) ProtoMessage() {}

func (x *GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_game_v1_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfo.ProtoReflect.Descriptor instead.
func (*GameInfo) Descriptor() ([]byte, []int) {
	return file_backend_game_v1_game_proto_rawDescGZIP(), []int{3}
}

func (x *GameInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GameInfo) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *GameInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GameInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GameInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GameInfo) GetImageCode() string {
	if x != nil {
		return x.ImageCode
	}
	return ""
}

func (x *GameInfo) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

type UpdateGamesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        int32                  `protobuf:"varint,1,opt,name=site_id,json=siteId,proto3" json:"site_id" dc:"站点ID"` // 站点ID
	Data          []*GameUpdateInfo      `protobuf:"bytes,2,rep,name=data,proto3" json:"data" dc:"游戏更新数据"`                  // 游戏更新数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGamesReq) Reset() {
	*x = UpdateGamesReq{}
	mi := &file_backend_game_v1_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGamesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGamesReq) ProtoMessage() {}

func (x *UpdateGamesReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_game_v1_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGamesReq.ProtoReflect.Descriptor instead.
func (*UpdateGamesReq) Descriptor() ([]byte, []int) {
	return file_backend_game_v1_game_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateGamesReq) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *UpdateGamesReq) GetData() []*GameUpdateInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GameUpdateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"游戏ID"`                 // 游戏ID
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status" dc:"状态 1=启用 0=禁用"` // 状态 1=启用 0=禁用
	Sort          int32                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort" dc:"排序"`               // 排序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameUpdateInfo) Reset() {
	*x = GameUpdateInfo{}
	mi := &file_backend_game_v1_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameUpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameUpdateInfo) ProtoMessage() {}

func (x *GameUpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_game_v1_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameUpdateInfo.ProtoReflect.Descriptor instead.
func (*GameUpdateInfo) Descriptor() ([]byte, []int) {
	return file_backend_game_v1_game_proto_rawDescGZIP(), []int{5}
}

func (x *GameUpdateInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameUpdateInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GameUpdateInfo) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type UpdateGamesRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success" dc:"是否成功"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message" dc:"响应消息"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGamesRes) Reset() {
	*x = UpdateGamesRes{}
	mi := &file_backend_game_v1_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGamesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGamesRes) ProtoMessage() {}

func (x *UpdateGamesRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_game_v1_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGamesRes.ProtoReflect.Descriptor instead.
func (*UpdateGamesRes) Descriptor() ([]byte, []int) {
	return file_backend_game_v1_game_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGamesRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateGamesRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_backend_game_v1_game_proto protoreflect.FileDescriptor

const file_backend_game_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x1abackend/game/v1/game.proto\x12\x04game\"M\n" +
	"\vGetGamesReq\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\x05R\x06siteId\x12%\n" +
	"\x0esearch_balance\x18\x02 \x01(\bR\rsearchBalance\"\xa1\x01\n" +
	"\vGetGamesRes\x12/\n" +
	"\x04data\x18\x01 \x03(\v2\x1b.game.GetGamesRes.DataEntryR\x04data\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x1aK\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.game.GameTypeListR\x05value:\x028\x01\"4\n" +
	"\fGameTypeList\x12$\n" +
	"\x05games\x18\x01 \x03(\v2\x0e.game.GameInfoR\x05games\"\xd6\x01\n" +
	"\bGameInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\x12\x12\n" +
	"\x04code\x18\a \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"image_code\x18\b \x01(\tR\timageCode\x12\x17\n" +
	"\adb_name\x18\t \x01(\tR\x06dbName\"S\n" +
	"\x0eUpdateGamesReq\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\x05R\x06siteId\x12(\n" +
	"\x04data\x18\x02 \x03(\v2\x14.game.GameUpdateInfoR\x04data\"L\n" +
	"\x0eGameUpdateInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x05R\x04sort\"D\n" +
	"\x0eUpdateGamesRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2w\n" +
	"\x04Game\x122\n" +
	"\bGetGames\x12\x11.game.GetGamesReq\x1a\x11.game.GetGamesRes\"\x00\x12;\n" +
	"\vUpdateGames\x12\x14.game.UpdateGamesReq\x1a\x14.game.UpdateGamesRes\"\x00B%Z#jh_game_service/api/backend/game/v1b\x06proto3"

var (
	file_backend_game_v1_game_proto_rawDescOnce sync.Once
	file_backend_game_v1_game_proto_rawDescData []byte
)

func file_backend_game_v1_game_proto_rawDescGZIP() []byte {
	file_backend_game_v1_game_proto_rawDescOnce.Do(func() {
		file_backend_game_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_game_v1_game_proto_rawDesc), len(file_backend_game_v1_game_proto_rawDesc)))
	})
	return file_backend_game_v1_game_proto_rawDescData
}

var file_backend_game_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_backend_game_v1_game_proto_goTypes = []any{
	(*GetGamesReq)(nil),    // 0: game.GetGamesReq
	(*GetGamesRes)(nil),    // 1: game.GetGamesRes
	(*GameTypeList)(nil),   // 2: game.GameTypeList
	(*GameInfo)(nil),       // 3: game.GameInfo
	(*UpdateGamesReq)(nil), // 4: game.UpdateGamesReq
	(*GameUpdateInfo)(nil), // 5: game.GameUpdateInfo
	(*UpdateGamesRes)(nil), // 6: game.UpdateGamesRes
	nil,                    // 7: game.GetGamesRes.DataEntry
}
var file_backend_game_v1_game_proto_depIdxs = []int32{
	7, // 0: game.GetGamesRes.data:type_name -> game.GetGamesRes.DataEntry
	3, // 1: game.GameTypeList.games:type_name -> game.GameInfo
	5, // 2: game.UpdateGamesReq.data:type_name -> game.GameUpdateInfo
	2, // 3: game.GetGamesRes.DataEntry.value:type_name -> game.GameTypeList
	0, // 4: game.Game.GetGames:input_type -> game.GetGamesReq
	4, // 5: game.Game.UpdateGames:input_type -> game.UpdateGamesReq
	1, // 6: game.Game.GetGames:output_type -> game.GetGamesRes
	6, // 7: game.Game.UpdateGames:output_type -> game.UpdateGamesRes
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_backend_game_v1_game_proto_init() }
func file_backend_game_v1_game_proto_init() {
	if File_backend_game_v1_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_game_v1_game_proto_rawDesc), len(file_backend_game_v1_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_game_v1_game_proto_goTypes,
		DependencyIndexes: file_backend_game_v1_game_proto_depIdxs,
		MessageInfos:      file_backend_game_v1_game_proto_msgTypes,
	}.Build()
	File_backend_game_v1_game_proto = out.File
	file_backend_game_v1_game_proto_goTypes = nil
	file_backend_game_v1_game_proto_depIdxs = nil
}
