// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// agGameDao is the data access object for the table ag_game.
// You can define custom methods on it to extend its functionality as needed.
type agGameDao struct {
	*internal.AgGameDao
}

var (
	// AgGame is a globally accessible object for table ag_game operations.
	AgGame = agGameDao{internal.NewAgGameDao()}
)

// Add your custom methods and functionality below.
