// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// agHunterDao is the data access object for the table ag_hunter.
// You can define custom methods on it to extend its functionality as needed.
type agHunterDao struct {
	*internal.AgHunterDao
}

var (
	// AgHunter is a globally accessible object for table ag_hunter operations.
	AgHunter = agHunterDao{internal.NewAgHunterDao()}
)

// Add your custom methods and functionality below.
