// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// agLiveDao is the data access object for the table ag_live.
// You can define custom methods on it to extend its functionality as needed.
type agLiveDao struct {
	*internal.AgLiveDao
}

var (
	// AgLive is a globally accessible object for table ag_live operations.
	AgLive = agLiveDao{internal.NewAgLiveDao()}
)

// Add your custom methods and functionality below.
