// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// agSportsDao is the data access object for the table ag_sports.
// You can define custom methods on it to extend its functionality as needed.
type agSportsDao struct {
	*internal.AgSportsDao
}

var (
	// AgSports is a globally accessible object for table ag_sports operations.
	AgSports = agSportsDao{internal.NewAgSportsDao()}
)

// Add your custom methods and functionality below.
