// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// bbinLotteryDao is the data access object for the table bbin_lottery.
// You can define custom methods on it to extend its functionality as needed.
type bbinLotteryDao struct {
	*internal.BbinLotteryDao
}

var (
	// BbinLottery is a globally accessible object for table bbin_lottery operations.
	BbinLottery = bbinLotteryDao{internal.NewBbinLotteryDao()}
)

// Add your custom methods and functionality below.
