// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// ebetLiveDao is the data access object for the table ebet_live.
// You can define custom methods on it to extend its functionality as needed.
type ebetLiveDao struct {
	*internal.EbetLiveDao
}

var (
	// EbetLive is a globally accessible object for table ebet_live operations.
	EbetLive = ebetLiveDao{internal.NewEbetLiveDao()}
)

// Add your custom methods and functionality below.
