// =================================================================================
// This file is auto-generated by GoFrame CLI tool only once. Fill this file with your own code.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// gameDao is the data access object for the table game.
// You can define custom methods on it to extend its functionality as needed.
type gameDao struct {
	*internal.GameDao
}

var (
	// Game is a globally accessible object for table game operations.
	Game = gameDao{internal.NewGameDao()}
)
