// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// hgLiveDao is the data access object for the table hg_live.
// You can define custom methods on it to extend its functionality as needed.
type hgLiveDao struct {
	*internal.HgLiveDao
}

var (
	// HgLive is a globally accessible object for table hg_live operations.
	HgLive = hgLiveDao{internal.NewHgLiveDao()}
)

// Add your custom methods and functionality below.
