// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// igJiliGameDao is the data access object for the table ig_jili_game.
// You can define custom methods on it to extend its functionality as needed.
type igJiliGameDao struct {
	*internal.IgJiliGameDao
}

var (
	// IgJiliGame is a globally accessible object for table ig_jili_game operations.
	IgJiliGame = igJiliGameDao{internal.NewIgJiliGameDao()}
)

// Add your custom methods and functionality below.
