// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// igPpGameDao is the data access object for the table ig_pp_game.
// You can define custom methods on it to extend its functionality as needed.
type igPpGameDao struct {
	*internal.IgPpGameDao
}

var (
	// IgPpGame is a globally accessible object for table ig_pp_game operations.
	IgPpGame = igPpGameDao{internal.NewIgPpGameDao()}
)

// Add your custom methods and functionality below.
