// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// igPgGameDao is the data access object for the table ig_pg_game.
// You can define custom methods on it to extend its functionality as needed.
type igPgGameDao struct {
	*internal.IgPgGameDao
}

var (
	// IgPgGame is a globally accessible object for table ig_pg_game operations.
	IgPgGame = igPgGameDao{internal.NewIgPgGameDao()}
)

// Add your custom methods and functionality below.
