// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// kyPokerDao is the data access object for the table ky_poker.
// You can define custom methods on it to extend its functionality as needed.
type kyPokerDao struct {
	*internal.KyPokerDao
}

var (
	// KyPoker is a globally accessible object for table ky_poker operations.
	KyPoker = kyPokerDao{internal.NewKyPokerDao()}
)

// Add your custom methods and functionality below.
