// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// lyPokerDao is the data access object for the table ly_poker.
// You can define custom methods on it to extend its functionality as needed.
type lyPokerDao struct {
	*internal.LyPokerDao
}

var (
	// LyPoker is a globally accessible object for table ly_poker operations.
	LyPoker = lyPokerDao{internal.NewLyPokerDao()}
)

// Add your custom methods and functionality below.
