// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// ogLiveDao is the data access object for the table og_live.
// You can define custom methods on it to extend its functionality as needed.
type ogLiveDao struct {
	*internal.OgLiveDao
}

var (
	// OgLive is a globally accessible object for table og_live operations.
	OgLive = ogLiveDao{internal.NewOgLiveDao()}
)

// Add your custom methods and functionality below.
