// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// oneApiGameDao is the data access object for the table one_api_game.
// You can define custom methods on it to extend its functionality as needed.
type oneApiGameDao struct {
	*internal.OneApiGameDao
}

var (
	// OneApiGame is a globally accessible object for table one_api_game operations.
	OneApiGame = oneApiGameDao{internal.NewOneApiGameDao()}
)

// Add your custom methods and functionality below.
