// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// ptGameDao is the data access object for the table pt_game.
// You can define custom methods on it to extend its functionality as needed.
type ptGameDao struct {
	*internal.PtGameDao
}

var (
	// PtGame is a globally accessible object for table pt_game operations.
	PtGame = ptGameDao{internal.NewPtGameDao()}
)

// Add your custom methods and functionality below.
