// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// ptHunterDao is the data access object for the table pt_hunter.
// You can define custom methods on it to extend its functionality as needed.
type ptHunterDao struct {
	*internal.PtHunterDao
}

var (
	// PtHunter is a globally accessible object for table pt_hunter operations.
	PtHunter = ptHunterDao{internal.NewPtHunterDao()}
)

// Add your custom methods and functionality below.
