// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_game_service/internal/dao/internal"
)

// sbSportsDao is the data access object for the table sb_sports.
// You can define custom methods on it to extend its functionality as needed.
type sbSportsDao struct {
	*internal.SbSportsDao
}

var (
	// SbSports is a globally accessible object for table sb_sports operations.
	SbSports = sbSportsDao{internal.NewSbSportsDao()}
)

// Add your custom methods and functionality below.
